// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:43dfae5b-7d52-4a2b-93dd-96842ad018f4",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_OBRIgbEfY",
    "aws_user_pools_web_client_id": "6rc23bvmrvi3j2di845vc19gln"
};


export default awsmobile;
